// This file is auto-generated by @hey-api/openapi-ts

export type Body_files_create_file = {
    file: (Blob | File);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CourseStep = {
    /**
     * 단계 (1: 식사, 2: 카페, 3: 놀거리/술)
     */
    step: number;
    /**
     * 카테고리 (식당, 카페, 이자카야 등)
     */
    category: string;
    /**
     * 네이버 검색용 최종 문자열 (4단어 이하)
     */
    final_query: string;
};

export type FilePublic = {
    filename: string;
    file_url?: (string | null);
    extracted_text?: (string | null);
    id: string;
    owner_id: string;
    created_at: string;
};

export type FilesPublic = {
    data: Array<FilePublic>;
    count: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type Metadata = {
    /**
     * 대화에서 추출한 핵심 지역 (없으면 '강남역')
     */
    location: string;
    /**
     * 모임 이름 (무조건 '친구 2인'으로 고정)
     */
    group_name: string;
    /**
     * 약속 날짜 (무조건 '2025년 12월 7일'로 고정)
     */
    date: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type Persona = {
    /**
     * 참여자 이름 (예: '나', '어피치')
     */
    name: string;
    /**
     * 대화에서 유추한 성격이나 취향을 요약한 한 문장
     */
    traits: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type RecommendationRequest = {
    file_id?: (string | null);
    courses?: (Array<CourseStep> | null);
    metadata?: (Metadata | null);
    personas?: (Array<Persona> | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type FilesCreateFileData = {
    formData: Body_files_create_file;
};

export type FilesCreateFileResponse = (FilePublic);

export type FilesReadFilesData = {
    limit?: number;
    skip?: number;
};

export type FilesReadFilesResponse = (FilesPublic);

export type FilesDeleteFileData = {
    id: string;
};

export type FilesDeleteFileResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type RecommendationsCreateRecommendationData = {
    requestBody: RecommendationRequest;
};

export type RecommendationsCreateRecommendationResponse = (unknown);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);